@Library("braze-jenkins-libs")_

node {

def gitSHA = ""

stage("scm") {
    checkout scm
    gitSHA = sh(returnStdout: true, script: "git log -n 1 --pretty=format:'%h'").trim()
}
stage("build") {
    dockerImageBuilder("braze-cluster-autoscaler", gitSHA, 'cluster-autoscaler', 'cluster-autoscaler/Dockerfile.amd64')
  }
}

